connection-check-wait = 0.5
ping-period = 5.0
server-host = "127.0.0.1"
server-port = 8000
log-level = "debug"
client-id = "pyhtmx-gui-client"
ovos-server-url = "ws://localhost:18181/gui"
cache-dir = "~/.cache/ovos_gui"
